spring:
  application:
    name: eureka-provider1
  cloud:
    config:
      enabled: true
  eureka:
    instance:
      hostname: provider1
#      preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://peer1:8763/eureka/,http://peer2:8762/eureka/
